"use client";

import { useState } from "react";
import Link from "next/link";

type Mode = "consumer" | "attorney";

interface ConsentModalProps {
  mode: Mode;
  onConsent: () => void;
  onCancel: () => void;
}

const CONSUMER_BULLETS = [
  <>This tool provides <strong className="text-text-primary">general information only</strong> — it does not provide legal advice and is not a substitute for consulting a licensed attorney.</>,
  <>No attorney-client relationship is created by using this service. Nothing you submit is privileged or confidential.</>,
  <>Answers are generated by AI from publicly available sources and may be inaccurate, incomplete, or outdated.</>,
  <>No response has been reviewed or approved by any attorney, law firm, or government agency.</>,
  <>You should independently verify any information before relying on it and consult an attorney about your specific situation.</>,
];

const ATTORNEY_BULLETS = [
  <>All output is AI-generated and <strong className="text-text-primary">requires independent verification</strong> — citations, statutory references, and legal analysis may contain errors.</>,
  <>When you use case workspace tools, we <strong className="text-text-primary">obfuscate identifying information</strong> (names, emails, phone numbers, case numbers) before sending excerpts to our AI provider. No obfuscation system is perfect — some identifying information may not be caught.</>,
  <>Your uploaded files are <strong className="text-text-primary">processed and stored locally</strong> on our servers. Only AI-generated analysis involves a third-party service (Anthropic), which does not train on API data and deletes it within 30 days.</>,
  <>You are <strong className="text-text-primary">solely responsible</strong> for determining whether AI-assisted analysis is appropriate for your matter, including obtaining any required client consent under applicable rules of professional conduct.</>,
  <>By continuing, you agree to the <Link href="/terms#section-11" className="text-accent underline hover:text-accent-hover">Terms of Use, including Section 11</Link> (AI Processing of Case Materials), and accept full responsibility for your use of these tools in connection with any client representation.</>,
];

const CONSUMER_CHECKBOX =
  "I understand that this is general information, not legal advice, and that I should consult a licensed attorney about my specific situation.";

const ATTORNEY_CHECKBOX =
  "I understand that AI-generated analysis requires verification, that entity obfuscation is not perfect, and that I am responsible for compliance with my professional obligations.";

export default function ConsentModal({ mode, onConsent, onCancel }: ConsentModalProps) {
  const [checked, setChecked] = useState(false);

  const bullets = mode === "consumer" ? CONSUMER_BULLETS : ATTORNEY_BULLETS;
  const checkboxText = mode === "consumer" ? CONSUMER_CHECKBOX : ATTORNEY_CHECKBOX;
  const heading =
    mode === "consumer"
      ? "Important Legal Notice"
      : "Professional Use Disclaimer";

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4">
      <div className="w-full max-w-lg rounded-xl bg-surface-raised border border-border p-6 shadow-2xl">
        <h2 className="text-lg font-bold text-text-primary">{heading}</h2>

        <ul className="mt-4 space-y-2 text-sm text-text-secondary">
          {bullets.map((bullet, i) => (
            <li key={i} className="flex gap-2">
              <span className="shrink-0">{i + 1}.</span>
              <span>{bullet}</span>
            </li>
          ))}
        </ul>

        <label className="mt-5 flex cursor-pointer items-start gap-3 text-sm text-text-secondary">
          <input
            type="checkbox"
            checked={checked}
            onChange={(e) => setChecked(e.target.checked)}
            className="mt-0.5 h-4 w-4 shrink-0 rounded accent-accent"
          />
          <span>{checkboxText}</span>
        </label>

        <p className="mt-3 text-xs text-text-tertiary">
          {mode === "attorney" ? (
            <>
              By continuing you agree to our{" "}
              <Link href="/terms" className="text-accent underline hover:text-accent-hover">
                Terms of Use
              </Link>
              {" "}including our{" "}
              <Link href="/privacy#case-file-data" className="text-accent underline hover:text-accent-hover">
                AI data processing practices
              </Link>
              .
            </>
          ) : (
            <>
              By continuing you agree to our{" "}
              <Link href="/terms" className="text-accent underline hover:text-accent-hover">
                Terms of Use
              </Link>
              .
            </>
          )}
        </p>

        <div className="mt-5 flex justify-end gap-3">
          <button
            type="button"
            onClick={onCancel}
            className="rounded-lg border border-border px-4 py-2 text-sm font-medium text-text-secondary transition-colors hover:bg-surface"
          >
            Cancel
          </button>
          <button
            type="button"
            onClick={onConsent}
            disabled={!checked}
            className="rounded-lg bg-accent px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-accent-hover disabled:cursor-not-allowed disabled:opacity-50"
          >
            Continue
          </button>
        </div>
      </div>
    </div>
  );
}
