import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Use — Free Legal Help",
  description:
    "Terms of Use for Free Legal Help, an AI-powered California employment law information tool.",
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:px-8">
      <nav className="mb-6 text-sm text-text-tertiary">
        <Link href="/" className="hover:text-accent">
          Home
        </Link>
        {" / "}
        <span className="text-text-primary">Terms of Use</span>
      </nav>

      <h1 className="text-3xl font-bold tracking-tight text-text-primary sm:text-4xl">
        Terms of Use
      </h1>
      <p className="mt-2 text-sm text-text-tertiary">
        Last updated: February 2026
      </p>

      <div className="mt-8 space-y-8 text-text-secondary leading-relaxed">
        <section>
          <h2 className="text-xl font-semibold text-text-primary">
            1. Acceptance of Terms
          </h2>
          <p className="mt-3">
            By accessing or using Free Legal Help (&quot;the Service&quot;), you
            agree to be bound by these Terms of Use. If you do not agree, do not
            use the Service.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">
            2. Nature of Service
          </h2>
          <p className="mt-3">
            The Service is an AI-powered chatbot that generates responses based
            on publicly available California legal sources, including state
            agency websites, statutory codes, and jury instructions. It is
            designed to provide general information about California employment
            law for educational purposes.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">
            3. Not Legal Advice
          </h2>
          <p className="mt-3">
            The information provided by the Service does not constitute legal
            advice. It is general information only and should not be relied upon
            as a substitute for consultation with a licensed attorney. No action
            should be taken based solely on the content provided by the Service.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">
            4. No Attorney-Client Relationship
          </h2>
          <p className="mt-3">
            Use of the Service does not create an attorney-client relationship.
            The Service is not operated by a law firm and does not provide legal
            representation. No communications through the Service are protected
            by attorney-client privilege. The Service does not represent you in
            any legal matter.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">
            5. Limitations of AI
          </h2>
          <p className="mt-3">
            Responses are generated by artificial intelligence and may contain
            inaccuracies, incomplete information, or outdated content. The AI may
            produce responses that appear authoritative but are factually
            incorrect (&quot;hallucinations&quot;). No response has been reviewed
            or verified by a licensed attorney or any other person.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">
            6. Data and Privacy
          </h2>
          <p className="mt-3">
            Questions you submit and the responses generated may be logged for
            the purpose of improving the Service. These logs are not reviewed by
            any person or law firm as part of normal operations. Do not submit
            personally identifiable information, confidential details about
            pending legal matters, or any information you would not want stored
            electronically.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">
            7. Disclaimer of Warranties
          </h2>
          <p className="mt-3">
            The Service is provided &quot;AS IS&quot; and &quot;AS
            AVAILABLE&quot; without warranties of any kind, whether express or
            implied, including but not limited to warranties of merchantability,
            fitness for a particular purpose, accuracy, or non-infringement.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">
            8. Limitation of Liability
          </h2>
          <p className="mt-3">
            To the fullest extent permitted by law, the operators of the Service
            shall not be liable for any direct, indirect, incidental, special,
            consequential, or punitive damages arising out of or relating to your
            use of or inability to use the Service, including any decisions made
            or actions taken in reliance on information provided by the Service.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">
            9. Recommended Actions
          </h2>
          <ul className="mt-3 list-disc space-y-2 pl-6">
            <li>
              Consult a licensed California employment attorney before taking any
              legal action.
            </li>
            <li>
              Independently verify any information provided by the Service using
              official government sources.
            </li>
            <li>
              Contact the relevant California agency (DIR, DFEH/CRD, EDD)
              directly for guidance on your specific situation.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-text-primary">
            10. Changes to Terms
          </h2>
          <p className="mt-3">
            We reserve the right to modify these Terms of Use at any time.
            Changes will be effective upon posting to this page. Your continued
            use of the Service after any modification constitutes acceptance of
            the updated Terms.
          </p>
        </section>
      </div>

      <div className="mt-10">
        <Link
          href="/"
          className="text-sm text-accent underline hover:text-accent-hover"
        >
          Back to Home
        </Link>
      </div>
    </div>
  );
}
